name: Linux Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
          architecture: 'x64'
      - name: Build
        run: |
          sed -i "s/v0.0.0/$(git describe --tags)/g" ./main.py
          sudo apt-get install -y upx
          pip install -r requirements.txt
          pyinstaller --noconsole -F ./main.py --icon icon.png -n personal-assistant
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/personal-assistant
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}